const mongoose = require('mongoose');

const PaymentCartItemSchema = new mongoose.Schema(
  {
    product: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Product',
      required: true,
    },
    quantity: { type: Number, required: true, min: 1 },
    priceAtPurchase: { type: Number, required: true, min: 0 }, // in SAR
  },
  { _id: false }
);

const PaymentSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // Stripe PaymentIntent id (set after we create the intent)
    stripePaymentIntentId: {
      type: String,
      required: false,
      index: true,
      unique: true,
      sparse: true,
    },

    // Idempotency key generated by our server for the same cart attempt
    idempotencyKey: { type: String, required: true, index: true, unique: true },

    status: {
      type: String,
      enum: [
        'initiated',
        'processing',
        'succeeded',
        'failed',
        'canceled',
        'refunded',
      ],
      default: 'initiated',
      index: true,
    },

    currency: { type: String, default: 'SAR' },

    // Amounts in SAR
    amountSubtotal: { type: Number, required: true },
    amountTax: { type: Number, required: true },
    amountShipping: { type: Number, required: false, default: 0 },
    amountTotal: { type: Number, required: true },

    cart: { type: [PaymentCartItemSchema], required: true },

    // Shipping is optional now (digital/treatment flows).
    // If you later add real delivery, you can re-enable required validation.
    shipping: {
      fullName: { type: String, required: false },
      email: { type: String, required: false },
      phone: { type: String, required: false },
      address: { type: String, required: false },
      city: { type: String, required: false },
      postalCode: { type: String, required: false },
    },

    // Set only when we create an Order from the payment
    order: { type: mongoose.Schema.Types.ObjectId, ref: 'Order' },
  },
  { timestamps: true }
);

PaymentSchema.set('toJSON', {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret.id = ret._id.toString();
    delete ret._id;
    return ret;
  },
});

module.exports = mongoose.model('Payment', PaymentSchema);

