const mongoose = require('mongoose');

const SubscriptionPaymentSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    // Stripe PaymentIntent id
    stripePaymentIntentId: {
      type: String,
      required: false,
      index: true,
      unique: true,
      sparse: true,
    },

    // Idempotency key generated by our server
    idempotencyKey: { type: String, required: true, index: true, unique: true },

    status: {
      type: String,
      enum: ['initiated', 'processing', 'succeeded', 'failed', 'canceled', 'refunded'],
      default: 'initiated',
      index: true,
    },

    currency: { type: String, default: 'SAR' },

    // Amounts in SAR
    amountTotal: { type: Number, required: true },

    // Role purchased: 'business'
    planRole: { type: String, enum: ['business'], required: true },

    paymentMethod: {
      type: String,
      enum: ['stripe', 'wish_money'],
      default: 'stripe',
      index: true,
    },

    // Wish Money transfer details (when paymentMethod=wish_money)
    wishTransfer: {
      senderFullName: { type: String },
      senderPhone: { type: String },
      transferReference: { type: String, index: true, unique: true, sparse: true },
      transferDate: { type: Date },
      submittedAt: { type: Date },
      verificationNote: { type: String },
      verifiedAt: { type: Date },
      verifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    },
  },
  { timestamps: true }
);

SubscriptionPaymentSchema.set('toJSON', {
  virtuals: true,
  versionKey: false,
  transform: (_, ret) => {
    ret.id = ret._id.toString();
    delete ret._id;
    return ret;
  },
});

module.exports = mongoose.model('SubscriptionPayment', SubscriptionPaymentSchema);

